### ISSUE TITLE
Реализация механики "труб"

### ISSUE THREAD

**Issue by Ionchenkova** [V3416TheRealRTZ/pipe_chat#10]
Реализация механики "труб" (добавление/удаление)

**Comment by Lipetskikh** [comment]
Тестировать можно с версии 19.11.2016_ 033

**Comment by elevir** [comment]
Проверено в версии 6_30.12.2016_ 126
Не отображаются трубы

**Comment by Lobachevskiy** [comment]
Исправлено в версии 7_10.01.2017_2338_115d192
