### ISSUE TITLE
Реализация сетевого соединения 

### ISSUE THREAD

**Issue by Ionchenkova** [V3416TheRealRTZ/pipe_chat#12]

**Comment by elevir** [comment]
Не устанавливается соединение клиента с сервером (сервер и клиент запущены на локальной машине).
Ошибка "Unable to connect. Connection refused by peer."

**Comment by Lipetskikh** [comment]
Тестировать можно с версии 19.11.2016_ 033

**Comment by Lobachevskiy** [comment]
Исправлено 4_20.12.2016_0028_fb2e52b

**Comment by elevir** [comment]
Протестировано в версии 5_20.12.2016_1712_d33bac2
